jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usermanagement?characterEncoding=UTF-8&serverTimezone=UTC
    password: 1234
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect